:_mod-docs-content-type: PROCEDURE

[id="configuring-a-ca-bundle-for-llama-stack_{context}"]
= Configuring a CA bundle for Llama Stack

[role="_abstract"]
To enable the Llama Stack server to trust certificates that are issued by a self-signed or private Certificate Authority (CA), reference a config map that contains the CA certificates from the `spec.server.tlsConfig.caBundle` field of your `LlamaStackDistribution` custom resource (CR).

[IMPORTANT]
====
When you complete this procedure, the Llama Stack Operator restarts the Llama Stack server pod so that the new certificates take effect. Plan for a brief service interruption when you apply or update the CA bundle on a `LlamaStackDistribution` CR that is serving production traffic.
====

ifndef::disconnected[]
The following procedure uses the best pattern of referencing the `odh-trusted-ca-bundle` config map, which {productname-short} automatically maintains in every non-reserved namespace. To use a dedicated config map, or to reference a config map in a different namespace, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed/working-with-certificates_certs#ca-bundle-configuration--for-llama-stack_certs[CA bundle configuration for Llama Stack] for the alternative configuration patterns.
endif::[]
ifdef::disconnected[]
The following procedure uses the best pattern of referencing the `odh-trusted-ca-bundle` config map, which {productname-short} automatically maintains in every non-reserved namespace. To use a dedicated config map, or to reference a config map in a different namespace, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed_in_a_disconnected_environment/working-with-certificates_certs#ca-bundle-configuration-for-llama-stack_certs[CA bundle configuration for Llama Stack] for the alternative configuration patterns.
endif::[]

.Prerequisites

* You have installed {openshift-platform} {ocp-minimum-version} or later.
* You have logged in to {productname-long}.
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have activated the Llama Stack Operator in {productname-short}. For more information, see link:{rhoaidocshome}{default-format-url}/working_with_llama_stack/activating-the-llama-stack-operator_llama-stack[Activating the Llama Stack Operator].
* You have deployed at least one `LlamaStackDistribution` instance in {productname-short}. For more information, see link:{rhoaidocshome}{default-format-url}/working_with_llama_stack/deploying-a-llamastackdistribution-instance_llama-stack[Deploying a LlamaStackDistribution instance].
ifndef::disconnected[]
* You have added the required CAs to the cluster-wide CA bundle or to a custom CA bundle, as described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed/working-with-certificates_certs#adding-certificates-to-a-cluster-ca-bundle_certs[Adding certificates to a cluster-wide CA bundle] and link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed/working-with-certificates_certs#adding-certificates-to-a-custom-ca-bundle_certs[Adding certificates to a custom CA bundle].
endif::[]
ifdef::disconnected[]
* You have added the required CAs to the cluster-wide CA bundle or to a custom CA bundle, as described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed_in_a_disconnected_environment/working-with-certificates_certs#adding-certificates-to-a-cluster-ca-bundle_certs[Adding certificates to a cluster-wide CA bundle] and link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed_in_a_disconnected_environment/working-with-certificates_certs#adding-certificates-to-a-custom-ca-bundle_certs[Adding certificates to a custom CA bundle].
endif::[]
* You have installed the {openshift-cli} as described in the appropriate documentation for your cluster:
** link:https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI] for {openshift-productname}.
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI] for {rosa-productname}.

.Procedure

. Log in to the {productname-short} web console as a cluster administrator.

. From the *Project* list, select the project that contains your `LlamaStackDistribution` CR.

. Confirm that the `odh-trusted-ca-bundle` config map is present in your project:

.. In the *Administrator* perspective, click *Workloads* -> *ConfigMaps*.

.. In the list of config maps, locate `odh-trusted-ca-bundle` and click its name.

.. Confirm that the config map contains the following two keys, both of which the Llama Stack Operator reads:
+
--
`ca-bundle.crt`::
The cluster-wide CA bundle that the Cluster Network Operator (CNO) injects.
`odh-ca-bundle.crt`::
Custom CAs that you have added through the `customCABundle` field of the DSCI object.
--

. Reference the `odh-trusted-ca-bundle` config map from your `LlamaStackDistribution` CR.

.. Click *Home* -> *Search*.

.. From the *Resources* list, search for `LlamaStackDistribution` and select it. The cluster also exposes a `LlamaStackOperator` resource, which is an internal {productname-short} resource that is managed by the {productname-long} Operator. Do not select `LlamaStackOperator`.

.. From the list of `LlamaStackDistribution` instances, click the name of the instance that you want to update.

.. Click the *YAML* tab.

.. Add a `tlsConfig.caBundle` field under `spec.server`, as shown in the following example:
+
[source,yaml]
----
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: my-llamastack
  namespace: my-llamastack-namespace
spec:
  replicas: 1
  server:
    distribution:
      name: rh-dev
    containerSpec:
      port: 8321
    tlsConfig:
      caBundle:
        configMapName: odh-trusted-ca-bundle <1>
        configMapKeys: <2>
          - ca-bundle.crt
          - odh-ca-bundle.crt
----
<1> Specifies the name of the source config map.
<2> Specifies the keys in the source config map that the Llama Stack Operator reads. The Llama Stack Operator concatenates the certificates from all listed keys into a single bundle.

.. Click *Save*. The Llama Stack server pod automatically redeploys with the updated bundle.

.Verification

. In a terminal window, log in to your {openshift-platform} cluster from the {openshift-cli}:
+
[subs="+quotes"]
----
$ oc login --token=__<token>__ --server=__<openshift_cluster_url>__
----

. Confirm that the Llama Stack Operator created the managed CA bundle config map. The managed config map is named `<instance-name>-ca-bundle`:
+
[subs="+quotes"]
----
$ oc get configmap __<instance-name>__-ca-bundle -n __<namespace>__
----
+
The output shows the managed config map.

. Confirm that the `LlamaStackDistribution` CR reports a successful CA bundle configuration in its status:
+
[subs="+quotes"]
----
$ oc get llamastackdistribution __<instance-name>__ -n __<namespace>__ -o yaml
----
+
In the `status.conditions` field of the output, verify that the `DeploymentReady` condition has `status: "True"` and that no condition reports a CA bundle validation failure in its `message` field.

. Confirm that the Llama Stack server pod is running with the CA bundle mounted:
+
[subs="+quotes"]
----
$ oc get pods -n __<namespace>__ -l app.kubernetes.io/instance=__<instance-name>__
----

. Confirm that the CA bundle file is present in the server container at the expected mount path and that the `SSL_CERT_FILE` environment variable points to it:
+
[subs="+quotes"]
----
$ oc exec -n __<namespace>__ __<pod-name>__ -- ls -l /etc/ssl/certs/ca-bundle/ca-bundle.crt
----
+
[subs="+quotes"]
----
$ oc exec -n __<namespace>__ __<pod-name>__ -- printenv SSL_CERT_FILE
----
+
The output of the `printenv` command shows `/etc/ssl/certs/ca-bundle/ca-bundle.crt`.

. Confirm that the bundle file contains the expected CA certificates:
+
[subs="+quotes"]
----
$ oc exec -n __<namespace>__ __<pod-name>__ -- \
  head -20 /etc/ssl/certs/ca-bundle/ca-bundle.crt
----
+
The output begins with a `-----BEGIN CERTIFICATE-----` line, followed by the encoded certificate data of the first certificate in the bundle.

. Confirm that the Llama Stack server can establish a trusted TLS connection to your external endpoint by sending a test request from inside the pod:
+
[subs="+quotes"]
----
$ oc exec -n __<namespace>__ __<pod-name>__ -- \
  curl -sS -o /dev/null -w "%{http_code}\n" __<external-endpoint-url>__
----
+
A successful HTTP status code, such as `200`, indicates that the certificate chain is validated. A `curl` error that mentions a self-signed certificate or a certificate verification failure indicates that the bundle does not include the correct issuing CA.