:_mod-docs-content-type: REFERENCE

[id="mlflow-workbench-environment-variables-reference_{context}"]
= MLflow workbench environment variables and annotations

[role="_abstract"]
When MLflow integration is enabled for a workbench, the notebook controller injects environment variables and creates RBAC resources automatically.
You can use this reference to understand the annotation, environment variables, and `RoleBinding` resource that the platform manages on your behalf.

[#mlflow-annotation_{context}]
== Annotation

.MLflow instance annotation
[cols="1,3", options="header"]
|===
|Annotation
|Description

|`opendatahub.io/mlflow-instance`
|Specifies the name of the MLflow instance CR to connect to.
When this annotation is present and non-empty on a notebook resource, the notebook controller enables MLflow integration for the workbench.
The annotation value determines the path segment in the tracking URI.
|===

.Annotation value to tracking URI path mapping
[cols="1,1", options="header"]
|===
|Annotation value
|Tracking URI path

|`mlflow`
|`/mlflow`

|`__<custom_instance_name>__`
|`/mlflow-__<custom_instance_name>__`
|===

[#mlflow-environment-variables_{context}]
== Environment variables

The following environment variables are injected into the notebook container when the `opendatahub.io/mlflow-instance` annotation is present.

.MLflow environment variables
[cols="2,2,3", options="header"]
|===
|Variable
|Value
|Description

|`MLFLOW_TRACKING_URI`
|`\https://__<gateway_hostname>__/mlflow` or `\https://__<gateway_hostname>__/mlflow-__<instance_name>__`
|Specifies the URL of the MLflow tracking server.
The hostname is derived from the GatewayAPI public endpoint.
If the instance name is `mlflow`, the path is `/mlflow`.
If the instance name differs from `mlflow`, the path is `/mlflow-__<instance_name>__`.

|`MLFLOW_K8S_INTEGRATION`
|`true`
|Specifies that the MLflow client uses Kubernetes service account token authentication.

|`MLFLOW_TRACKING_AUTH`
|`kubernetes-namespaced`
|Specifies the authentication method for the MLflow client.
This value configures namespace-scoped authentication using the workbench service account.
|===

[#mlflow-rolebinding_{context}]
== RoleBinding

The notebook controller creates a namespace-scoped `RoleBinding` resource for each annotated workbench.

.MLflow RoleBinding details
[cols="1,3", options="header"]
|===
|Property
|Value

|Name
|`__<notebook_name>__-mlflow`

|Namespace
|Same as the notebook resource namespace

|Subject
|`ServiceAccount` with the name of the notebook, in the notebook namespace

|RoleRef
|`ClusterRole` named `mlflow-operator-mlflow-integration`

|Controller owner reference
|Set to the notebook resource, so the `RoleBinding` is automatically deleted when the notebook is deleted

|Labels
|`notebook-name: __<notebook_name>__`
|===

[#mlflow-clusterrole-availability_{context}]
== ClusterRole availability

The `RoleBinding` resource references the `mlflow-operator-mlflow-integration` `ClusterRole` resource, which is created by the MLflow Operator.
If this `ClusterRole` resource does not yet exist when the reconciler attempts to create the `RoleBinding` resource, the reconciler requeues the request with a warning event every 30 seconds until the `ClusterRole` resource becomes available.
These events are generated only when a notebook resource has the `opendatahub.io/mlflow-instance` annotation, but the `ClusterRole` resource does not yet exist.
If no annotated notebooks exist, no events are generated.
You can observe these events by running the following command, where `__<namespace>__` is the namespace containing your workbench notebook:

[source,terminal]
----
$ oc get events -n __<namespace>__ --field-selector reason=MLflowClusterRolePending
----

[#mlflow-controller-environment-variables_{context}]
== Controller environment variables

The {productname-long} Operator automatically configures the following environment variables on the notebook controller when the `mlflowoperator` component is set to `Managed` in the `DataScienceCluster` object.
You do not need to set these variables manually.

.Controller environment variables
[cols="2,3", options="header"]
|===
|Variable
|Description

|`MLFLOW_ENABLED`
|Set to `true` when the `mlflowoperator` component is `Managed` in the `DataScienceCluster` object.
Enables the notebook controller to process MLflow annotations on workbench resources.

|`GATEWAY_URL`
|Set based on the cluster's Gateway configuration.
The notebook controller uses this value to construct the `MLFLOW_TRACKING_URI` for workbench pods.
|===
