#!/usr/bin/env bash
# Commit manifest-listed files and push the feature branch.
# Usage: bash commit.sh <ticket-id> --base-path <path> [--repo-path <path>] [--draft]
set -euo pipefail

# --- Argument parsing ---
TICKET=""
BASE_PATH=""
REPO_PATH=""
DRAFT=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-path) BASE_PATH="$2"; shift 2 ;;
    --repo-path) REPO_PATH="$2"; shift 2 ;;
    --draft) DRAFT=true; shift ;;
    -*) echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
    *)
      if [[ -z "$TICKET" ]]; then
        TICKET="$1"
      else
        echo "ERROR: Unexpected argument: $1" >&2
        exit 1
      fi
      shift
      ;;
  esac
done

[[ -z "$TICKET" ]] && { echo "ERROR: Ticket ID is required." >&2; exit 1; }
[[ -z "$BASE_PATH" ]] && { echo "ERROR: --base-path is required." >&2; exit 1; }

TICKET_LOWER="$(echo "$TICKET" | tr '[:upper:]' '[:lower:]')"
OUTPUT_DIR="${BASE_PATH}/commit"
mkdir -p "$OUTPUT_DIR"
COMMIT_SHA=""

# --- Helper: write commit-info.json ---
# Args: <pushed: true|false> [file1 file2 ...]
# Uses BRANCH, COMMIT_SHA, PLATFORM, REPO_URL from script scope.
write_commit_info() {
  local pushed="$1"; shift
  python3 -c "
import json, sys
print(json.dumps({
    'branch': sys.argv[1] or None,
    'commit_sha': sys.argv[2] or None,
    'files_committed': list(sys.argv[6:]),
    'platform': sys.argv[3] or None,
    'repo_url': sys.argv[4] or None,
    'pushed': sys.argv[5] == '1'
}, indent=2))
" "${BRANCH:-}" "${COMMIT_SHA:-}" "${PLATFORM:-}" "${REPO_URL:-}" \
  "$([ "$pushed" = true ] && echo 1 || echo 0)" "$@" \
  > "${OUTPUT_DIR}/commit-info.json"
}

# --- Draft mode: skip ---
if [[ "$DRAFT" == true ]]; then
  write_commit_info false
  echo "Draft mode — skipped committing."
  exit 0
fi

# --- Resolve repo context from --repo-path or cwd ---
REPO_DIR=""
REPO_URL=""
PLATFORM=""
BRANCH=""

resolve_dir="${REPO_PATH:-$(pwd)}"
if ! git -C "$resolve_dir" rev-parse --git-dir >/dev/null 2>&1; then
  echo "ERROR: ${resolve_dir} is not a git repository." >&2
  exit 1
fi

REPO_DIR="$(git -C "$resolve_dir" rev-parse --show-toplevel)"
BRANCH="$(git -C "$resolve_dir" rev-parse --abbrev-ref HEAD)"
REPO_URL="$(git -C "$resolve_dir" remote get-url origin 2>/dev/null || echo "")"

if echo "$REPO_URL" | grep -qi "github.com"; then
  PLATFORM="github"
elif echo "$REPO_URL" | grep -qi "gitlab"; then
  PLATFORM="gitlab"
else
  PLATFORM="unknown"
fi

echo "Repo:     ${REPO_DIR}"
echo "Branch:   ${BRANCH}"
echo "Platform: ${PLATFORM}"
echo "Remote:   ${REPO_URL}"

# --- Safety checks ---
if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
  echo "ERROR: Refusing to push to '${BRANCH}'. All pushes must go to feature branches." >&2
  exit 1
fi

# --- Read manifest ---
MANIFEST="${BASE_PATH}/writing/_index.md"

if [[ ! -f "$MANIFEST" ]]; then
  echo "No manifest found at ${MANIFEST}."
  write_commit_info false
  exit 0
fi

# Extract file paths from the manifest table that are under the repo directory.
# Manifest rows: | /absolute/path/to/file.md | TYPE | Description |
# Also handles backtick-wrapped paths: | `/absolute/path/to/file.md` | ...
REPO_DIR_ABS="$(cd "$REPO_DIR" && pwd)"
readarray -t MANIFEST_FILES < <(python3 -c "
import sys, re
clone = sys.argv[1]
with open(sys.argv[2]) as f:
    for line in f:
        for m in re.findall(r'\|\s*\x60?(' + re.escape(clone) + r'\S+?)\x60?\s*(?:\||$)', line):
            print(m)
" "$REPO_DIR_ABS" "$MANIFEST" 2>/dev/null)

if [[ ${#MANIFEST_FILES[@]} -eq 0 ]]; then
  echo "No files found in manifest under ${REPO_DIR_ABS}."
  write_commit_info false
  exit 0
fi

# --- Stage manifest files ---
cd "$REPO_DIR_ABS"
STAGED_FILES=()
for filepath in "${MANIFEST_FILES[@]}"; do
  if [[ -f "$filepath" ]]; then
    git add "$filepath" || { echo "WARNING: failed to stage ${filepath}" >&2; continue; }
    STAGED_FILES+=("${filepath#${REPO_DIR_ABS}/}")
  else
    echo "WARNING: Manifest lists ${filepath} but file does not exist. Skipping." >&2
  fi
done

# Check if anything was actually staged
if [[ ${#STAGED_FILES[@]} -eq 0 ]] || git diff --cached --quiet; then
  echo "No changes to commit."
  write_commit_info false
  exit 0
fi

# --- Commit ---
git commit -m "docs(${TICKET_LOWER}): add generated documentation

Files:
$(printf '  - %s\n' "${STAGED_FILES[@]}")

Generated by docs-pipeline for ${TICKET}" 2>&1

COMMIT_SHA=$(git rev-parse HEAD)
echo "Committed: ${COMMIT_SHA}"

# --- Push ---
git fetch origin "$BRANCH" 2>/dev/null || true

# --force-with-lease: pipeline-generated branches, not collaborative work.
# Re-runs create a fresh branch from main, diverging from the remote.
if git push --force-with-lease -u origin "$BRANCH" 2>&1; then
  echo "Pushed branch '${BRANCH}' to origin"
  write_commit_info true "${STAGED_FILES[@]}"
else
  echo "ERROR: Push failed. Branch committed locally but not pushed." >&2
  write_commit_info false "${STAGED_FILES[@]}"
  exit 1
fi

echo "Wrote ${OUTPUT_DIR}/commit-info.json"
