:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="openai-compatible-file-citation-annotations"]
= OpenAI-compatible file citation annotations

:context: openai-compatible-file-citation-annotations

[role="_abstract"]
Llama Stack supports OpenAI-compatible file citation annotations in Responses API outputs when using the `file_search` tool.
You can use these annotations to trace generated responses back to source documents without changing existing OpenAI client code.

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
File citation annotations are currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
File citation annotations are currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

include::modules/openai-file-citation-annotations-in-llama-stack.adoc[leveloffset=+1]
include::modules/viewing-file-citation-annotations-in-responses-api-output.adoc[leveloffset=+1]
include::modules/viewing-file-citation-annotations-in-llama-stack-ui.adoc[leveloffset=+1]
include::modules/file-citation-annotation-reference.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
