:_module-type: PROCEDURE

[id="creating-secrets-for-the-external-s3-files-provider_{context}"]
= Creating secrets for the external S3-compatible files provider

[role="_abstract"]
To authenticate Llama Stack to an external S3-compatible object storage service by using access keys, create a Kubernetes secret that contains the credentials.

If you intend to use IAM roles for service accounts (IRSA) or another short-lived credential mechanism, you can skip this procedure and configure the role binding for your Llama Stack service account instead.

.Prerequisites

* You have access to the project where your Llama Stack resources are deployed.
* You have the access key ID and secret access key for your S3-compatible storage backend, or you have configured an IAM role for the Llama Stack service account.

.Procedure

. Log in to your {openshift-platform} cluster from the CLI:
+
[source,terminal,subs="+quotes"]
----
$ oc login --token=__<token>__ --server=__<openshift_cluster_url>__
----

. Create a secret that contains the S3 credentials:
+
[source,terminal,subs="+quotes"]
----
$ oc create secret generic s3-files-credentials \
  --from-literal=AWS_ACCESS_KEY_ID=__<access_key_id>__ \
  --from-literal=AWS_SECRET_ACCESS_KEY=__<secret_access_key>__ \
  -n __<project>__
----
+
In the previous command, replace `<access_key_id>` with the access key ID for your S3-compatible storage backend. Replace `<secret_access_key>` with the secret access key for your S3-compatible storage backend. Replace `<project>` with the name of the project where the `LlamaStackDistribution` resource is deployed.

.Verification

* The S3 credentials secret exists in the project. You can confirm this by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc get secret s3-files-credentials -n __<project>__
----